server:
  port: 5010

spring:
  application:
    name: user-service

  flyway:
    url: jdbc:postgresql://localhost:5432/botlemon_application
    locations: classpath:db/migration
    user: root
    password: 1
    default-schema: migration

  jpa:
    show-sql: false
    open-in-view: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/botlemon_application
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/