server:
  port: 5020

spring:
  application:
    name: user-service

  jpa:
    show-sql: false
    open-in-view: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/botlemon_application
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/