server:
  port: 5022

spring:
  application:
    name: order-service

  jpa:
    show-sql: false
    open-in-view: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/botlemon_application
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1

  jwt:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 864000

#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/